Try to fix the flaky snapshot_generator test
We occasionally saw this test fail with the error

    java.lang.OutOfMemoryError: Java heap space

Since we only need "just a bit more than 10000", we can reduce the
amount of memory we use without affecting the test, and hopefully it
will fail less often.